[package]
name = "epidemic"
version = "0.1.0"
authors = ["paddywwoof <patrick@eldwick.org.uk>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
image = "0.23.2"
serde = {version = "1.0.105", features = ["derive"]}
serde_json = "1.0.50"
scoped_threadpool = "0.1.*"